version: "3.9"

services:
  api:
    build: .
    container_name: scorex-beckend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - scorex-net

  db:
    image: postgres:15-alpine
    container_name: scorex-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - scorex-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - scorex-net

volumes:
  scorex-db-data:

networks:
  scorex-net:
    driver: bridge
